# Generated by Django 4.1.5 on 2023-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateField(auto_now_add=True, verbose_name='Transaction Date')),
                ('details', models.CharField(max_length=250, verbose_name='Details')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('isIncome', models.BooleanField(default=True, verbose_name='Is Income')),
            ],
        ),
    ]
